"""update defect schema

Revision ID: 316e394a3170
Revises: 5caf88cb9d8c
Create Date: 2026-09-03 22:09:36.482511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316e394a3170'
down_revision: Union[str, Sequence[str], None] = '5caf88cb9d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defects',
    sa.Column('defect_id', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('defect_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('detected_date', sa.Date(), nullable=False),
    sa.Column('target_resolution_date', sa.Date(), nullable=False),
    sa.Column('estimated_repair_hours', sa.Integer(), nullable=False),
    sa.Column('safety_risk', sa.Integer(), nullable=False),
    sa.Column('operational_impact', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('defect_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defects')
    # ### end Alembic commands ###
