"""create initial railway schema

Revision ID: 5caf88cb9d8c
Revises: 
Create Date: 2026-09-03 20:33:25.351588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5caf88cb9d8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corridors',
    sa.Column('corridor_id', sa.String(length=10), nullable=False),
    sa.Column('corridor_name', sa.String(length=100), nullable=False),
    sa.Column('start_km', sa.Float(), nullable=False),
    sa.Column('end_km', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('corridor_id')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.String(length=10), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.String(length=10), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('corridor_id', sa.String(length=10), nullable=False),
    sa.Column('location_km', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.Column('last_maintenance_date', sa.Date(), nullable=False),
    sa.Column('next_maintenance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.corridor_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('goods_forecasts',
    sa.Column('forecast_id', sa.String(length=20), nullable=False),
    sa.Column('corridor_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('expected_goods_trains', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.corridor_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_table('trains',
    sa.Column('train_id', sa.String(length=20), nullable=False),
    sa.Column('corridor_id', sa.String(length=10), nullable=False),
    sa.Column('train_number', sa.String(length=20), nullable=False),
    sa.Column('train_type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.corridor_id'], ),
    sa.PrimaryKeyConstraint('train_id')
    )
    op.create_table('defects',
    sa.Column('defect_id', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reported_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('defect_id')
    )
    op.create_table('maintenance_tasks',
    sa.Column('task_id', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('estimated_duration_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('block_requests',
    sa.Column('block_request_id', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.String(length=20), nullable=False),
    sa.Column('corridor_id', sa.String(length=10), nullable=False),
    sa.Column('location_km', sa.Float(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.corridor_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('block_request_id')
    )
    op.create_table('optimized_blocks',
    sa.Column('optimized_block_id', sa.String(length=20), nullable=False),
    sa.Column('block_request_id', sa.String(length=20), nullable=False),
    sa.Column('corridor_id', sa.String(length=10), nullable=False),
    sa.Column('block_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('department_count', sa.Integer(), nullable=False),
    sa.Column('optimization_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['block_request_id'], ['block_requests.block_request_id'], ),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.corridor_id'], ),
    sa.PrimaryKeyConstraint('optimized_block_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimized_blocks')
    op.drop_table('block_requests')
    op.drop_table('maintenance_tasks')
    op.drop_table('defects')
    op.drop_table('trains')
    op.drop_table('goods_forecasts')
    op.drop_table('assets')
    op.drop_table('departments')
    op.drop_table('corridors')
    # ### end Alembic commands ###
