"""add priority score and level

Revision ID: 8687e9d410de
Revises: 316e394a3170
Create Date: 2026-09-03 23:02:24.966593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8687e9d410de'
down_revision: Union[str, Sequence[str], None] = '316e394a3170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_tasks', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('maintenance_tasks', sa.Column('priority_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_tasks', 'priority_level')
    op.drop_column('maintenance_tasks', 'priority_score')
    # ### end Alembic commands ###
