"""add optimized block request association

Revision ID: a27720afd8f1
Revises: 8687e9d410de
Create Date: 2026-09-04 00:31:13.191829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27720afd8f1'
down_revision: Union[str, Sequence[str], None] = '8687e9d410de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimized_block_requests',
    sa.Column('optimized_block_id', sa.String(length=20), nullable=False),
    sa.Column('block_request_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['block_request_id'], ['block_requests.block_request_id'], ),
    sa.ForeignKeyConstraint(['optimized_block_id'], ['optimized_blocks.optimized_block_id'], ),
    sa.PrimaryKeyConstraint('optimized_block_id', 'block_request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimized_block_requests')
    # ### end Alembic commands ###
