import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import {
  CalendarClock,
  Clock3,
  Route,
  Search,
  RefreshCw,
  Layers3,
  TrendingUp,
  UsersRound,
  CheckCircle2,
  ChevronDown,
  Zap,
} from "lucide-react";

const API_URL = import.meta.env.VITE_API_URL || "http://127.0.0.1:8000";

function BlockPlanning() {
  const [blocks, setBlocks] = useState([]);
  const [search, setSearch] = useState("");
  const [corridor, setCorridor] = useState("All");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedBlock, setSelectedBlock] = useState(null);
  const [detailsLoading, setDetailsLoading] = useState(false);

  const fetchBlocks = () => {
    setLoading(true);
    setError(null);

    fetch(`${API_URL}/api/optimized-blocks/`)
      .then((response) => {
        if (!response.ok) {
          throw new Error("Unable to load optimized blocks");
        }

        return response.json();
      })
      .then((data) => {
        setBlocks(Array.isArray(data) ? data : []);
      })
      .catch((err) => {
        setError(err.message);
      })
      .finally(() => {
        setLoading(false);
      });
  };

  useEffect(() => {
    fetchBlocks();
  }, []);

  const handleBlockClick = async (blockId) => {
    try {
      setDetailsLoading(true);

      const response = await fetch(
        `${API_URL}/api/optimized-block-details/${blockId}`,
      );

      if (!response.ok) {
        throw new Error("Unable to load block details");
      }

      const data = await response.json();
      setSelectedBlock(data);
    } catch (error) {
      console.error("Block details error:", error);
    } finally {
      setDetailsLoading(false);
    }
  };

  const corridors = useMemo(() => {
    return [
      "All",
      ...new Set(blocks.map((block) => block.corridor_id).filter(Boolean)),
    ];
  }, [blocks]);

  const filteredBlocks = useMemo(() => {
    return blocks.filter((block) => {
      const text = search.toLowerCase();

      const matchesSearch =
        block.optimized_block_id?.toLowerCase().includes(text) ||
        block.corridor_id?.toLowerCase().includes(text) ||
        block.block_date?.toLowerCase().includes(text);

      const matchesCorridor =
        corridor === "All" || block.corridor_id === corridor;

      return matchesSearch && matchesCorridor;
    });
  }, [blocks, search, corridor]);

  const statistics = useMemo(() => {
    const totalHours = blocks.reduce(
      (sum, block) => sum + Number(block.duration_hours || 0),
      0,
    );

    const coordinated = blocks.filter(
      (block) => Number(block.department_count || 0) > 1,
    ).length;

    const averageScore =
      blocks.length > 0
        ? blocks.reduce(
            (sum, block) => sum + Number(block.optimization_score || 0),
            0,
          ) / blocks.length
        : 0;

    return {
      total: blocks.length,
      totalHours,
      coordinated,
      averageScore,
    };
  }, [blocks]);

  return (
    <div className="space-y-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end">
          <div>
            <div className="mb-2 flex items-center gap-2">
              <CalendarClock className="h-4 w-4 text-blue-400" />

              <span className="text-xs font-medium uppercase tracking-[0.18em] text-blue-400">
                AI Optimization
              </span>
            </div>

            <h1 className="text-2xl font-bold tracking-tight text-white sm:text-3xl">
              Block Planning
            </h1>

            <p className="mt-2 max-w-2xl text-sm text-slate-400">
              Optimized maintenance blocks generated by the railway planning
              engine while coordinating operational constraints.
            </p>
          </div>

          <button
            onClick={fetchBlocks}
            className="flex w-fit items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm text-slate-300 transition hover:border-blue-400/20 hover:bg-blue-400/10 hover:text-white"
          >
            <RefreshCw className="h-4 w-4" />
            Refresh
          </button>
        </div>
      </motion.div>

      {/* Statistics */}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {[
          [
            "Optimized Blocks",
            statistics.total,
            CalendarClock,
            "text-blue-400",
          ],
          [
            "Planned Hours",
            `${statistics.totalHours.toFixed(1)} hrs`,
            Clock3,
            "text-cyan-400",
          ],
          [
            "Coordinated Blocks",
            statistics.coordinated,
            UsersRound,
            "text-violet-400",
          ],
          [
            "Average Score",
            statistics.averageScore.toFixed(2),
            TrendingUp,
            "text-emerald-400",
          ],
        ].map(([title, value, Icon, iconColor], index) => (
          <motion.div
            key={title}
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.07 }}
            className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"
          >
            <div className="flex items-center justify-between">
              <p className="text-xs text-slate-500">{title}</p>
              <Icon className={`h-4 w-4 ${iconColor}`} />
            </div>

            <p className="mt-3 text-2xl font-bold text-white">{value}</p>
          </motion.div>
        ))}
      </div>

      {/* Optimization banner */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.25 }}
        className="relative overflow-hidden rounded-2xl border border-blue-400/15 bg-blue-500/[0.05] p-5"
      >
        <div className="absolute -right-20 -top-20 h-40 w-40 rounded-full bg-blue-500/10 blur-3xl" />

        <div className="relative flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10 ring-1 ring-blue-400/10">
              <Zap className="h-5 w-5 text-blue-400" />
            </div>

            <div>
              <p className="text-sm font-semibold text-white">
                Optimization Engine
              </p>

              <p className="mt-1 text-xs text-slate-500">
                CP-SAT planning results are being used for block scheduling.
              </p>
            </div>
          </div>

          <span className="flex w-fit items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs text-emerald-300">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
            Optimized
          </span>
        </div>
      </motion.div>

      {/* Filters */}
      <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-4">
        <div className="flex flex-col gap-3 lg:flex-row">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />

            <input
              type="text"
              placeholder="Search block, corridor or date..."
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              className="w-full rounded-xl border border-white/10 bg-black/10 py-2.5 pl-10 pr-4 text-sm text-white outline-none placeholder:text-slate-600 focus:border-blue-400/30 focus:ring-2 focus:ring-blue-400/10"
            />
          </div>

          <div className="relative">
            <select
              value={corridor}
              onChange={(event) => setCorridor(event.target.value)}
              className="w-full appearance-none rounded-xl border border-white/10 bg-[#0a1628] px-4 py-2.5 pr-10 text-sm text-slate-300 outline-none focus:border-blue-400/30 sm:w-48"
            >
              {corridors.map((item) => (
                <option key={item} value={item}>
                  {item === "All" ? "All corridors" : item}
                </option>
              ))}
            </select>

            <ChevronDown className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />
          </div>
        </div>
      </div>

      {/* Block list */}
      <div className="rounded-2xl border border-white/10 bg-white/[0.035]">
        <div className="border-b border-white/10 px-5 py-4">
          <h2 className="text-sm font-semibold text-white">
            Optimized Maintenance Blocks
          </h2>

          <p className="mt-1 text-xs text-slate-500">
            Showing {filteredBlocks.length} of {blocks.length} optimized blocks
          </p>
        </div>

        {loading ? (
          <div className="space-y-3 p-5">
            {[1, 2, 3, 4, 5].map((item) => (
              <div
                key={item}
                className="h-24 animate-pulse rounded-xl bg-white/5"
              />
            ))}
          </div>
        ) : error ? (
          <div className="p-10 text-center">
            <CalendarClock className="mx-auto h-8 w-8 text-red-400" />

            <p className="mt-3 text-sm text-slate-300">{error}</p>

            <p className="mt-2 text-xs text-slate-500">
              Check that the optimized-block API is available.
            </p>
          </div>
        ) : (
          <div className="divide-y divide-white/5">
            {filteredBlocks.slice(0, 100).map((block, index) => {
              const isCoordinated = Number(block.department_count || 0) > 1;

              return (
                <motion.div
                  key={block.optimized_block_id}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{
                    delay: Math.min(index * 0.02, 0.4),
                  }}
                  className="group cursor-pointer p-5 transition-colors hover:bg-white/[0.025]"
                  onClick={() => handleBlockClick(block.optimized_block_id)}
                >
                  <div className="flex flex-col gap-5 xl:flex-row xl:items-center">
                    {/* Block identity */}
                    <div className="flex min-w-[220px] items-center gap-3">
                      <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue-500/10 ring-1 ring-blue-400/10">
                        <CalendarClock className="h-5 w-5 text-blue-400" />
                      </div>

                      <div>
                        <p className="font-mono text-xs font-semibold text-blue-300">
                          {block.optimized_block_id}
                        </p>

                        <p className="mt-1 text-xs text-slate-500">
                          {block.block_date}
                        </p>
                      </div>
                    </div>

                    {/* Timeline */}
                    <div className="flex flex-1 items-center gap-4">
                      <div className="min-w-[110px]">
                        <p className="text-[10px] uppercase tracking-wider text-slate-600">
                          Start
                        </p>

                        <p className="mt-1 font-mono text-sm text-white">
                          {block.start_time}
                        </p>
                      </div>

                      <div className="flex flex-1 items-center gap-2">
                        <div className="h-px flex-1 bg-gradient-to-r from-blue-500/40 to-cyan-400/40" />

                        <span className="rounded-full border border-white/10 bg-white/5 px-2.5 py-1 font-mono text-[10px] text-slate-400">
                          {block.duration_hours} hrs
                        </span>

                        <div className="h-px flex-1 bg-gradient-to-r from-cyan-400/40 to-blue-500/40" />
                      </div>

                      <div className="min-w-[110px] text-right">
                        <p className="text-[10px] uppercase tracking-wider text-slate-600">
                          End
                        </p>

                        <p className="mt-1 font-mono text-sm text-white">
                          {block.end_time}
                        </p>
                      </div>
                    </div>

                    {/* Details */}
                    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 xl:min-w-[420px]">
                      <div>
                        <p className="text-[10px] uppercase tracking-wider text-slate-600">
                          Corridor
                        </p>

                        <div className="mt-1 flex items-center gap-1.5">
                          <Route className="h-3.5 w-3.5 text-blue-400" />
                          <span className="text-xs text-slate-300">
                            {block.corridor_id}
                          </span>
                        </div>
                      </div>

                      <div>
                        <p className="text-[10px] uppercase tracking-wider text-slate-600">
                          Departments
                        </p>

                        <div className="mt-1 flex items-center gap-1.5">
                          <Layers3 className="h-3.5 w-3.5 text-violet-400" />
                          <span className="text-xs text-slate-300">
                            {block.department_count}
                          </span>
                        </div>
                      </div>

                      <div>
                        <p className="text-[10px] uppercase tracking-wider text-slate-600">
                          Score
                        </p>

                        <div className="mt-1 flex items-center gap-2">
                          <div className="h-1.5 w-14 overflow-hidden rounded-full bg-white/10">
                            <div
                              className="h-full rounded-full bg-blue-400"
                              style={{
                                width: `${Math.min(
                                  Number(block.optimization_score || 0),
                                  100,
                                )}%`,
                              }}
                            />
                          </div>

                          <span className="font-mono text-xs text-slate-300">
                            {Number(block.optimization_score || 0).toFixed(1)}
                          </span>
                        </div>
                      </div>

                      <div>
                        <p className="text-[10px] uppercase tracking-wider text-slate-600">
                          Status
                        </p>

                        <div className="mt-1 flex items-center gap-1.5">
                          <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400" />
                          <span className="text-xs text-emerald-300">
                            {block.status || "Planned"}
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Coordination indicator */}
                  {isCoordinated && (
                    <div className="mt-4 flex items-center gap-2 rounded-xl border border-violet-400/10 bg-violet-400/[0.04] px-3 py-2">
                      <UsersRound className="h-3.5 w-3.5 text-violet-400" />

                      <p className="text-[11px] text-violet-300">
                        Multi-department block — coordinated maintenance
                        opportunity
                      </p>
                    </div>
                  )}
                </motion.div>
              );
            })}
          </div>
        )}

        {!loading && !error && filteredBlocks.length === 0 && (
          <div className="p-10 text-center">
            <Search className="mx-auto h-8 w-8 text-slate-600" />

            <p className="mt-3 text-sm text-slate-400">
              No optimized blocks match your filters.
            </p>
          </div>
        )}
      </div>
      {selectedBlock && (
        <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/60 p-4 backdrop-blur-sm">
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 10 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            className="my-auto flex max-h-[calc(100vh-2rem)] w-full max-w-3xl flex-col overflow-hidden rounded-2xl border border-white/10 bg-[#0b1729] shadow-2xl"
          >
            <div className="flex items-center justify-between border-b border-white/10 px-6 py-5">
              <div>
                <p className="text-xs uppercase tracking-wider text-blue-400">
                  Optimized Block
                </p>

                <h2 className="mt-1 text-xl font-bold text-white">
                  {selectedBlock.optimized_block_id}
                </h2>
              </div>

              <button
                onClick={() => setSelectedBlock(null)}
                className="rounded-lg border border-white/10 px-3 py-1.5 text-sm text-slate-400 transition hover:bg-white/5 hover:text-white"
              >
                Close
              </button>
            </div>
            <div className="min-h-0 flex-1 overflow-y-auto">
              <div className="grid gap-4 p-6 sm:grid-cols-2 lg:grid-cols-4">
                <div>
                  <p className="text-xs text-slate-500">Corridor</p>
                  <p className="mt-1 text-sm font-semibold text-white">
                    {selectedBlock.corridor_id}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-slate-500">Date</p>
                  <p className="mt-1 text-sm font-semibold text-white">
                    {selectedBlock.block_date}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-slate-500">Time</p>
                  <p className="mt-1 text-sm font-semibold text-white">
                    {selectedBlock.start_time} - {selectedBlock.end_time}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-slate-500">Departments</p>
                  <p className="mt-1 text-sm font-semibold text-white">
                    {selectedBlock.department_count}
                  </p>
                </div>
              </div>

              <div className="border-t border-white/10 px-6 py-5">
                <h3 className="text-sm font-semibold text-white">
                  Coordinated Maintenance Requests
                </h3>

                <div className="mt-4 space-y-3">
                  {selectedBlock.block_requests.map((request) => (
                    <div
                      key={request.block_request_id}
                      className="rounded-xl border border-white/10 bg-white/[0.03] p-4"
                    >
                      <div className="flex flex-col justify-between gap-2 sm:flex-row">
                        <div>
                          <p className="font-mono text-sm text-blue-300">
                            {request.block_request_id}
                          </p>

                          <p className="mt-1 text-sm text-slate-300">
                            Task: {request.task_id}
                          </p>
                        </div>

                        <span className="h-fit rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">
                          {request.status}
                        </span>
                      </div>

                      <div className="mt-3 grid gap-2 text-xs text-slate-500 sm:grid-cols-3">
                        <span>Location: {request.location_km} km</span>
                        <span>
                          Requested: {request.start_time} - {request.end_time}
                        </span>
                        <span>Duration: {request.duration_hours} hrs</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}

export default BlockPlanning;
